enum EquipmentPreset {
  DHAROKS,
  MAX_MAGE_SHADOW,
  MAX_MAGE,
  MAX_MELEE,
  MAX_MELEE_SCYTHE,
  MAX_RANGED_TWISTED_BOW,
  MAX_RANGED_BLOWPIPE,
  MID_LEVEL_MAGE,
  MID_LEVEL_MELEE,
  MID_LEVEL_RANGED,
  VERACS,
  VOID_MAGE,
  VOID_MELEE,
  VOID_RANGED,
  TANK,
}

export default EquipmentPreset;
