FROM python:3-alpine AS scraper

RUN mkdir -p /workspace/scripts /workspace/cdn
COPY ./scripts/* /workspace/scripts
WORKDIR /workspace/scripts

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt
CMD ["sh", "-c", "python generateEquipment.py && python generateMonsters.py"]



FROM node:20-buster AS webapp

RUN mkdir -p /workspace
WORKDIR /workspace
COPY . /workspace

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn/v6 \
    yarn install
CMD ["yarn", "dev"]
